spring:
  datasource:
    url: jdbc:postgresql://localhost:54362/ng-trans
    username: admin
    password: admin

  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: true